---
# defaults file for roles/bind

dns_domain_name: example.com
host_domain_name: ocp.example.com
cluster_name: ocp
cluster_network: 192.168.121
hostname: ns1
host_octet: 253
dns:
  #  These IPs is not considered as good practice. For testing only.
  - forwarder1: 1.1.1.1
  - forwarder2: 8.8.8.8
