galaxy_info:
  author: Dzintars Klavins
  description: simple minimal bind9 server setup
  company: Oswee

  # if the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  # choose a valid license id from https://spdx.org - some suggested licenses:
  # - bsd-3-clause (default)
  # - mit
  # - gpl-2.0-or-later
  # - gpl-3.0-only
  # - apache-2.0
  # - cc-by-4.0
  license: gpl-2.0-or-later

  min_ansible_version: 2.1

  # if this a container enabled role, provide the minimum ansible container version.
  # min_ansible_container_version:

  #
  # provide a list of supported platforms, and for each platform a list of versions.
  # if you don't wish to enumerate all versions for a particular platform, use 'all'.
  # to view available platforms and versions (or releases), visit:
  # https://galaxy.ansible.com/api/v1/platforms/
  #
  platforms:
  - name: Fedora
    versions:
    - 33
  #   - 25
  # - name: someplatform
  #   versions:
  #   - all
  #   - 1.0
  #   - 7
  #   - 99.99

  galaxy_tags: []
    # list tags for your role here, one per line. a tag is a keyword that describes
    # and categorizes the role. users find roles by searching for tags. be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # note: a tag is limited to a single word comprised of alphanumeric characters.
    #       maximum 20 tags per role.

dependencies:
- name: dzintars.ansible.bind
  vars:
    network_interface_name: '{{ dns_network_interface }}'
