---
# tasks file for roles/bind

- name: copy named.conf and zone files
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: named
    group: named
    setype: named_conf_t
    mode: '0644'
  loop:
    - {src: 'named.conf.j2', dest: '/etc/named.conf'}
    - {src: 'zone.j2', dest: '/var/named/{{ cluster_name }}.{{ dns_domain_name }}.zone'}
    - {src: 'arpa.zone.j2', dest: "/var/named/{{ cluster_network | ipaddr('revdns') | regex_replace('^[0-9]+\\.', '') }}zone"}
  notify: restart named

- name: deploy resolv.conf template
  template:
    src: 'resolv.conf.j2'
    dest: /etc/resolv.conf
    setype: named_conf_t
    # owner: root
    # group: root
    mode: 0644
    # backup: yes
  notify:
    - restart NetworkManager

- name: add an Ethernet connection with static IP configuration
  nmcli:
    conn_name: eth0
    type: ethernet
    dns4: '{{ cluster_network }}.{{ host_octet }}'
    dns4_search: '{{ cluster_name }}.{{ dnd_domain_name | default("example.com")}}'
    state: present
  notify:
    - restart NetworkManager

# - name: set qemu user in /etc/sysconfig/network-scripts/ifcfg-enp1s0
#   lineinfile:
#     dest: /etc/sysconfig/network-scripts/ifcfg-enp1s0
#     regexp: "{{ item.pattern }}"
#     line: "{{ item.value }}"
#     state: present
#   loop:
#     - {pattern: '^DNS1=', value: 'DNS1="192.168.1.254"'}
#   notify:
#     - restart NetworkManager
