---
# tasks file for roles/bind
# - name: Set a hostname
#   become: yes
#   ansible.builtin.hostname:
#     name: ns1

- name: Copy Bind configuration
  become: yes
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: named
    group: named
    setype: named_conf_t
    mode: '0644'
  notify: restart named

- name: Copy zone files
  become: yes
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: named
    group: named
    setype: named_conf_t
    mode: '0644'
  loop:
    - {src: 'zone.j2', dest: '/var/named/{{ cluster_name }}.{{ dns_domain_name }}.zone'}
    - {src: 'arpa.zone.j2', dest: "/var/named/{{ cluster_network | ipaddr('revdns') | regex_replace('^[0-9]+\\.', '') }}zone"}
  notify:
    - restart named
    - restart firewalld

- name: Deploy resolv.conf template
  become: yes
  template:
    src: 'resolv.conf.j2'
    dest: /etc/resolv.conf
    setype: named_conf_t
    # owner: root
    # group: root
    mode: 0644
    # backup: yes
  notify:
    - restart NetworkManager

- name: Add an Ethernet connection with static IP configuration
  become: yes
  nmcli:
    conn_name: '{{ network_interface_name }}'
    type: ethernet
    dns4: '{{ cluster_network }}.{{ host_octet | default("253") }}'
    dns4_search: '{{ cluster_name }}.{{ dns_domain_name | default("example.com") }}'
    state: present
  notify:
    - restart NetworkManager

# - name: set qemu user in /etc/sysconfig/network-scripts/ifcfg-enp1s0
#   lineinfile:
#     dest: /etc/sysconfig/network-scripts/ifcfg-enp1s0
#     regexp: "{{ item.pattern }}"
#     line: "{{ item.value }}"
#     state: present
#   loop:
#     - {pattern: '^DNS1=', value: 'DNS1="192.168.1.254"'}
#   notify:
#     - restart NetworkManager
