---

- name: Configure workstations
  hosts: WORKSTATION
  become: no

  roles:
    - role: minio
    - role: dzintars.ansible.vault
    - role: dzintars.ansible.terraform
      vars:
        become_user: vagrant
