---

- name: Configure Workstation
  hosts: workstations
  connection: local
  gather_facts: yes
  become: no

  roles:
    - role: minio
      tags:
        - minio
    - role: dzintars.ansible.vault
      tags:
        - vault
    - role: dzintars.ansible.terraform
      tags:
        - terraform
      vars:
        terraform_version: 0.14.7
