---

- name: Configure Workstation
  hosts: workstations
  connection: local
  gather_facts: yes
  become: no

  roles:
    - role: oswee.ansible.golang
      tags:
        - golang
      vars:
        golang_version: 1.16.6
    - role: minio
      tags:
        - minio
    - role: oswee.ansible.vault
      tags:
        - vault
    - role: oswee.ansible.terraform
      tags:
        - terraform
      vars:
        terraform_version: 1.0.3
    - role: oswee.ansible.bazel
      tags:
        - bazel
    - role: oswee.ansible.nodejs
      tags:
        - nodejs
    - role: oswee.ansible.helm
      tags:
        - helm
    - role: oswee.ansible.nvim
      tags:
        - nvim
    # - role: oswee.ansible.sway
    #   tags:
    #     - sway
    - role: oswee.ansible.zsh
      tags:
        - zsh
    - role: oswee.ansible.obsidian
      tags:
        - obsidian
    - role: oswee.ansible.alacritty
      tags:
        - alacritty
    - role: oswee.ansible.git
      tags:
        - git
    - role: oswee.ansible.tmux
      tags:
        - tmux
    - role: oswee.ansible.slack
      tags:
        - slack
    - role: oswee.ansible.libvirt
      tags:
        - libvirt
      vars:
        libvirt_dir_iso: "/home/{{ become_user }}/kvm/iso"
        libvirt_dir_images: "/home/{{ become_user }}/kvm/images"
        libvirt_dir_pools: "/home/{{ become_user }}/kvm/pools"
    - role: oswee.ansible.mariadb
      tags:
        - mariadb
