---

- name: Configure Workstation
  hosts: workstations
  connection: local
  gather_facts: yes
  become: no

  roles:
    - role: oswee.ansible.golang
      tags:
        - golang
      vars:
        golang_version: 1.16.5
    - role: minio
      tags:
        - minio
    - role: oswee.ansible.vault
      tags:
        - vault
    - role: oswee.ansible.terraform
      tags:
        - terraform
      vars:
        terraform_version: 0.14.7
    - role: oswee.ansible.bazel
      tags:
        - bazel
    - role: oswee.ansible.nodejs
      tags:
        - nodejs
    - role: oswee.ansible.helm
      tags:
        - helm
