---

- name: Configure Workstation
  hosts: workstations
  connection: local
  gather_facts: yes
  become: no

  # collections:
  #   - oswee.ansible

  roles:
    - role: oswee.general.golang
      tags:
        - golang
      vars:
        golang_version: 1.16.6
    - role: minio
      tags:
        - minio
    - role: oswee.general.vault
      tags:
        - vault
    - role: oswee.general.terraform
      tags:
        - terraform
      vars:
        terraform_version: 1.0.3
    - role: oswee.general.bazel
      tags:
        - bazel
    - role: oswee.general.nodejs
      tags:
        - nodejs
    - role: oswee.general.helm
      tags:
        - helm
    - role: oswee.general.nvim
      tags:
        - nvim
    - role: oswee.general.sway
      tags:
        - sway
    - role: oswee.general.swaylock
      tags:
        - swaylock
    - role: oswee.general.sddm
      tags:
        - sddm
    - role: oswee.general.zsh
      tags:
        - zsh
    - role: oswee.general.obsidian
      tags:
        - obsidian
    - role: oswee.general.alacritty
      tags:
        - alacritty
    - role: oswee.general.git
      tags:
        - git
    - role: oswee.general.tmux
      tags:
        - tmux
    - role: oswee.general.slack
      tags:
        - slack
    - role: oswee.general.libvirt
      tags:
        - libvirt
      vars:
        libvirt_dir_iso: "/home/{{ become_user }}/kvm/iso"
        libvirt_dir_images: "/home/{{ become_user }}/kvm/images"
        libvirt_dir_pools: "/home/{{ become_user }}/kvm/pools"
    - role: oswee.general.mariadb
      tags:
        - mariadb
    - role: quay
      tags:
        - quay
    - role: haproxy
      tags:
        - haproxy
    - role: oswee.general.vagrant
      tags:
        - vagrant
    - role: oswee.general.molecule
      tags:
        - molecule
    - role: oswee.general.github
      tags:
        - github
