---
# - name: Converge
#   hosts: all
#   tasks:
#     - name: "Include ansible"
#       include_role:
#         name: "ansible"

- name: Workstation
  import_playbook: ../../workstation.yml

- name: Bastion
  import_playbook: ../../bastion.yml
