---
- name: Ignite
  hosts: WORKSTATION
  connection: local
  gather_facts: yes
  become: no

  tasks:
  - name: Debug
    ansible.builtin.debug:
      msg:
      - "Hello"

  - name: Facts
    ansible.builtin.debug:
      var: ansible_facts

  roles:
  - role: dzintars.minio
  - role: minio
