---
# defaults file for roles/matchbox

rhcos_baseurl: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.7/latest
nightly_rhcos_baseurl: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/latest

bios: rhcos-4.7.0-x86_64-metal.x86_64.raw.gz
kernel: rhcos-4.7.0-x86_64-live-kernel-x86_64
initramfs: rhcos-4.7.0-x86_64-live-initramfs.x86_64.img

nightly_bios: "rhcos-42.80.20191002.0-metal-bios.raw.gz"
nightly_kernel: "rhcos-42.80.20191002.0-installer-kernel"
nightly_initramfs: "rhcos-42.80.20191002.0-installer-initramfs.img"
